import axios from "axios";
export default function Home() {
  const final = [];
  const fail = [];
  const urlList=[
    "http://www.66girls.co.kr/",
    "http://www.sappun.co.kr",
    "http://www.slowand.com/",
    "http://chaakan.co.kr/",
    "http://www.banharu.com",
    "http://www.pinkelephant.co.kr",
    "http://merryaround.co.kr",
    "http://www.laurenhi.com",
    "http://bbongbra.co.kr/",
    "http://www.hotping.co.kr",
    "http://www.ganaesra.com/",
    "http://www.hypnotic.co.kr",
    "https://www.skullpig.com/",
    "http://habi-unni.com",
    "http://www.alittle-b.com/",
    "http://beginning.kr",
    "http://www.pinkage.co.kr/",
    "http://www.ba-on.com",
    "http://ggsing.com",
    "http://www.shoemaru.com",
    "http://www.withyoon.com",
    "http://www.iniesta.co.kr/",
    "http://www.monobabie.com/",
    "https://www.creamcheese.co.kr/",
    "http://www.itshu.co.kr/",
    "http://twee.co.kr/",
    "http://shopperland.co.kr",
    "http://www.manymore.co.kr/",
    "http://www.choper.kr/",
    "http://www.ultrafashion.net",
    "http://www.awab.co.kr/",
    "http://hn-hn.co.kr/",
    "http://www.in-themode.com",
    "http://www.noncode.co.kr/",
    "http://loveme.kr",
    "http://www.hollyshop.co.kr/",
    "http://www.wingbling.co.kr/",
    "http://www.looknone.co.kr",
    "http://www.manymanymode.com",
    "http://matesales.com",
    "http://www.baddiary.com/",
    "http://www.dorocy.co.kr/",
    "http://www.ifemme.co.kr/",
    "http://cherrykoko.com/",
    "http://love-minuet.com/",
    "http://www.hanstyle.tv/",
    "http://secretlabel.co.kr",
    "http://www.thecara.co.kr/",
    "http://www.milkcocoa.co.kr",
    "http://www.sweetplus.co.kr/",
    "http://www.vivaruby.co.kr",
    "http://www.twinsis.co.kr/",
    "http://www.common-unique.com",
    "http://www.ode.co.kr/",
    "http://www.jmine.net",
    "http://www.annadiva.com/",
    "http://www.roniel.co.kr/",
    "http://www.justone.co.kr/",
    "http://www.styleonme.com/",
    "http://www.nanasalon.com/",
    "http://www.build.co.kr/",
    "http://www.deepny.com/",
    "http://vi-shop.kr/",
    "http://nibbuns.co.kr/",
    "http://www.under-vi.com/",
    "http://www.zizhel.net",
    "http://k-club.co.kr",
    "http://www.chicfox.co.kr",
    "http://www.dodry.net/",
    "http://anais.co.kr",
    "http://www.45th.co.kr/",
    "http://www.midasb.co.kr",
    "http://mjcong.co.kr",
    "http://loloten.com/",
    "http://www.ojluxury.com/",
    "http://www.twang.co.kr/",
    "http://www.trendy-apparel.co.kr/",
    "http://gumzzi.co.kr",
    "http://www.ellpe.co.kr/",
    "http://www.nicehong.com/",
    "http://gogirl.co.kr",
    "http://kwonjo.co.kr",
    "http://www.orange-flower.co.kr/",
    "http://www.citynwoman.com/",
    "http://www.pur-ple.co.kr/",
    "http://bylogin.co.kr/",
    "http://www.gonyshop.com/",
    "http://www.boen.co.kr/",
    "http://www.fashion-full.com",
    "http://www.another-j.com/",
    "http://www.smokyalice.com/",
    "http://pighip.co.kr/",
    "https://linennatural.com/",
    "http://www.havanasunday.com",
    "http://marant.kr",
    "http://www.roxygirl.tv/",
    "http://www.annarich.co.kr/",
    "http://www.bluepops.co.kr/",
    "http://www.dailyjou.com/",
    "http://chocomom.com",
    "http://www.limishop.co.kr/",
    "http://www.olssen.co.kr/",
    "http://www.iammari.com/",
    "http://www.comesta.co/",
    "http://www.fine-thankyou.com/",
    "http://www.happy10.co.kr/",
    "http://www.labambaroom.com/",
    "http://www.9grab.com/",
    "http://www.melrosemood.com/",
    "http://www.moondal.com/",
    "http://www.by-sun.com/",
    "http://www.lalame.net/",
    "http://misscandy.co.kr",
    "http://www.momnuri.com",
    "http://shes-story.co.kr",
    "http://hrb.kr",
    "http://www.iampretty.tv/",
    "http://www.mayddle.com",
    "http://www.timelady.co.kr/",
    "http://www.tiramisustyle.com/",
    "http://www.shehj.com",
    "http://www.freckle.kr/",
    "http://aftermonday.com",
    "http://www.ready-2-wear.co.kr",
    "http://secondesecon.com/",
    "http://feelings.co.kr/",
    "http://www.everymorning.co.kr/",
    "http://www.g-r-a-b.com",
    "http://candyglow.co.kr/",
    "http://www.high-eny.co.kr/",
    "http://www.merryat.com/",
    "http://joyu.co.kr/",
    "http://www.coco-m.co.kr/",
    "http://www.vivishoeshoe.com",
    "http://www.lountess.com",
    "http://www.addmore.co.kr",
    "http://www.realmommy.co.kr/",
    "http://www.up-closet.com/",
    "http://bbibbongunni.com",
    "http://www.junjewelry.com/",
    "http://www.rozley.co.kr",
    "http://www.mimididi.co.kr/",
    "http://www.likeher.kr/",
    "http://www.myfiona.co.kr",
    "http://www.vanillasecond.com",
    "http://www.sagestore.co.kr/product/list.html?cate_no=24",
    "http://www.luvmiu.com",
    "http://www.thecocomj.co.kr/",
    "http://www.apuesto.co.kr",
    "http://www.springcomma.com/",
    "http://www.femmemuse.co.kr",
    "http://www.bluecoco.co.kr/",
    "http://threecut.kr/",
    "http://dparks.co.kr/",
    "http://www.i-arden.com/",
    "http://www.pink-rocket.com",
    "http://www.byyoom.co.kr/",
    "http://sundayup.co.kr",
    "http://yonifit.co.kr",
    "http://www.goldria.net",
    "http://www.everafter.kr",
    "http://jtamtam.co.kr/",
    "http://heigl.kr/",
    "http://www.whosgirl.co.kr",
    "http://binary01.co.kr",
    "http://www.gogobeach.co.kr/",
    "http://www.m-jade.co.kr",
    "http://02sister.com",
    "http://www.creccendo.com/",
    "http://www.graymadonna.com/",
    "http://www.camelbrown.com/",
    "http://www.nanajean.co.kr/",
    "http://www.tograndmother.co.kr/",
    "http://www.loveandpop.kr/",
    "http://www.bullang.com/",
    "http://onepound.kr/",
    "http://www.dona-d.com/",
    "http://simkung.co.kr",
    "http://www.jooen.com/",
    "http://www.finchvill.com/",
    "https://gifteabox.com",
    "http://www.show-me.kr/",
    "http://www.jblanc.kr/",
    "http://theresheis.kr/index.html",
    "http://darllyshop.co.kr/",
    "http://www.osimoto.co.kr/",
    "http://nabiang.com",
    "http://www.robinu.co.kr/",
    "http://www.youbyeolna.com",
    "http://www.merongshop.com/",
    "http://www.localmansion.com/",
    "http://www.a-monotone.com",
    "http://www.openithere.com/",
    "http://lalaroom.co.kr",
    "http://www.crazygirls.co.kr/",
    "http://www.gosister.co.kr",
    "http://another-language.com/",
    "http://www.mu-mu.co.kr/",
    "http://blank9.com/",
    "http://www.nadri4u.com",
    "http://www.styletiba.com/",
    "http://www.amai.co.kr/",
    "http://bonjourproject.kr/",
    "http://www.906studio.co.kr/",
    "http://www.gabangpop.co.kr",
    "http://www.arnewstyle.com/",
    "http://urban-rosy.com/",
    "http://chaefit.com",
    "http://the-mono.com",
    "http://www.derang.me/",
    "http://www.planj.co.kr",
    "http://www.dailymarket.kr/",
    "http://simpleboutique.co.kr/",
    "http://hotissue.or.kr",
    "http://www.ping-nugget.com/",
    "http://belin.co.kr",
    "http://www.hwangbarbie.com/",
    "http://21dressroom.com/",
    "http://www.wiarae.com/",
    "http://www.tongkeungirl.com",
    "http://www.windygirl.co.kr/",
    "http://dryrose.co.kr/",
    "http://www.meltingblue.co.kr/",
    "http://www.pak-namae.com",
    "http://www.exabra.com",
    "http://vivashoo.co.kr",
    "http://alldayu.com",
    "http://lavu.co.kr/",
    "https://peachvin.com/",
    "http://flat-80.com/",
    "http://p-sophia.com/",
    "http://www.comeonvincent.com",
    "http://dressupp.net",
    "http://www.zanne.co.kr/",
    "http://www.nabyup.com",
    "http://www.roseheel.com/",
    "http://ibelin.co.kr",
    "http://luxyqueen.net/",
    "http://www.holia.co.kr/",
    "http://www.cho2shop.com",
    "http://cocogen.co.kr/",
    "http://www.momentdive.co.kr/",
    "http://www.saintmary.co.kr",
    "http://bebeche.com",
    "http://www.280days.co.kr/",
    "http://www.thedalkom.co.kr/",
    "http://www.somedayif.com",
    "http://www.byme.co.kr/",
    "http://www.alicegohome.co.kr/",
    "http://moodinslow.com",
    "http://www.roer.co.kr",
    "http://newmonday.co.kr/",
    "http://www.flybeach.co.kr",
    "http://www.yebbum.co.kr/",
    "http://stdevos.com",
    "http://www.withmoment.co.kr",
    "http://www.close-clip.com",
    "http://www.vividplan.co.kr/",
    "http://www.lalabong.co.kr/",
    "http://www.stayon.co.kr/",
    "http://melted.co.kr/",
    "http://maysome.com",
    "http://www.dangolunni.com",
    "http://abgle.co.kr",
    "http://maylime.co.kr",
    "http://www.buttonoff.co.kr",
    "http://shoes-opening.com",
    "http://www.ernieandz.com/",
    "http://theyoons.co.kr",
    "http://www.peachpicnic.com/",
    "http://cherryville.co.kr",
    "http://www.hijjoo.com",
    "http://www.itme.kr/",
    "http://www.white-fox.co.kr",
    "http://hana-beach.com",
    "http://www.xn--2n1ba37ju43bca.com/",
    "http://thecollective.co.kr/",
    "http://blingshop.co.kr",
    "http://bubbledoll.kr/",
    "http://www.merrydate.co.kr/",
    "http://benign.co.kr/",
    "http://www.levernis.co.kr",
    "http://leming.co.kr",
    "http://www.byyenn.co.kr/",
    "http://www.taranco.co.kr/",
    "http://www.dal-som.com/",
    "http://merryaround.co.kr",
    "http://www.inthe-moment.co.kr/",
    "http://bbongbra.co.kr/",
    "http://www.laurenhi.com",
    "http://www.ganaesra.com/",
    "http://www.hypnotic.co.kr",
    "http://habi-unni.com",
    "http://www.alittle-b.com/",
    "http://www.pinkage.co.kr/",
    "http://www.ba-on.com",
    "https://www.skullpig.com/",
    "http://ggsing.com",
    "http://www.shoemaru.com",
    "http://www.withyoon.com",
    "http://www.iniesta.co.kr/",
    "https://www.creamcheese.co.kr/",
    "http://www.monobabie.com/",
    "http://www.itshu.co.kr/",
    "http://shopperland.co.kr",
    "http://twee.co.kr/",
    "http://www.manymore.co.kr/",
    "http://www.ultrafashion.net",
    "http://www.choper.kr/",
    "http://www.awab.co.kr/",
    "http://www.in-themode.com",
    "http://hn-hn.co.kr/",
    "http://loveme.kr",
    "http://www.noncode.co.kr/",
    "http://www.wingbling.co.kr/",
    "http://www.hollyshop.co.kr/",
    "http://www.manymanymode.com",
    "http://matesales.com",
    "http://www.looknone.co.kr",
    "http://www.dorocy.co.kr/",
    "http://www.blann.co.kr/"
]
  // const urlList = [
  //   "http://www.hotping.co.kr",
  //   "http://xexymix.com",
  //   "http://www.66girls.co.kr/",
  //   "http://www.sappun.co.kr",
  //   "http://www.slowand.com/",
  //   "http://chaakan.co.kr/",
  //   "http://www.banharu.com",
  //   "http://beginning.kr",
  //   "http://www.pinkelephant.co.kr",
  //   "http://www.black-up.kr/",
  //   "http://98doci.com",
  //   "http://merryaround.co.kr",
  //   "http://www.laurenhi.com",
  //   "http://www.ganaesra.com/",
  //   "http://ggsing.com",
  //   "http://bbongbra.co.kr/",
  //   "http://habi-unni.com",
  //   "http://www.sovomall.co.kr",
  //   "http://www.hypnotic.co.kr",
  //   "http://www.dorosiwa.co.kr/",
  //   "https://www.skullpig.com/",
  //   "http://www.alittle-b.com/",
  //   "http://thezam.co.kr",
  //   "http://www.recipeofgirl.com/",
  //   "http://www.pinkage.co.kr/",
  //   "http://www.ba-on.com",
  //   "http://www.withyoon.com",
  //   "http://www.itshu.co.kr/",
  //   "http://goldpang.com/",
  //   "http://richmood.co.kr/",
  //   "http://www.henique.co.kr/",
  //   "http://www.shoemaru.com",
  //   "http://www.monobabie.com/",
  //   "http://www.iniesta.co.kr/",
  //   "http://perbit.co.kr/",
  //   "http://www.sonyunara.com/",
  //   "http://www.rilly.co.kr",
  //   "https://www.creamcheese.co.kr/",
  //   "http://twee.co.kr/",
  //   "http://shopperland.co.kr",
  //   "http://soo-soo.co.kr",
  //   "http://vinvle.com/",
  //   "http://www.kikiko.co.kr/",
  //   "http://hn-hn.co.kr/",
  //   "http://www.choper.kr/",
  //   "http://www.manymore.co.kr/",
  //   "http://www.awab.co.kr/",
  //   "http://www.ultrafashion.net",
  //   "http://www.wingbling.co.kr/",
  //   "http://www.realyellow.co.kr/",
  //   "http://www.qng.co.kr",
  //   "http://www.in-themode.com",
  //   "http://loveme.kr",
  //   "http://matesales.com",
  //   "http://www.noncode.co.kr/",
  //   "http://www.hollyshop.co.kr/",
  //   "http://www.vanillashu.co.kr/",
  //   "http://www.manymanymode.com",
  //   "http://www.looknone.co.kr",
  //   "http://www.dorocy.co.kr/",
  //   "http://www.mombbe.co.kr/",
  //   "http://www.lylon.co.kr/",
  //   "http://www.baddiary.com/",
  //   "http://chic-line.com/",
  //   "http://cherrykoko.com/",
  //   "http://www.ifemme.co.kr/",
  //   "http://liphop.co.kr",
  //   "http://zoozoom.co.kr",
  //   "http://www.lemite.com/",
  //   "http://98doci.com",
  //   "http://www.mazia.kr/",
  //   "http://love-minuet.com/",
  //   "http://secretlabel.co.kr",
  //   "http://www.e-rin.co.kr/",
  //   "http://merryaround.co.kr",
  //   "http://www.themood.co.kr",
  //   "http://www.laurenhi.com",
  //   "http://www.common-unique.com",
  //   "http://www.milkcocoa.co.kr",
  //   "http://www.ganaesra.com/",
  //   "http://www.hanstyle.tv/",
  //   "http://www.thecara.co.kr/",
  //   "http://www.sweetplus.co.kr/",
  //   "http://www.vivaruby.co.kr",
  //   "http://ggsing.com",
  //   "http://bbongbra.co.kr/",
  //   "http://www.twinsis.co.kr/",
  //   "http://www.justone.co.kr/",
  //   "http://www.ode.co.kr/",
  //   "http://www.zizhel.net",
  //   "http://www.ribbontie.co.kr",
  //   "http://www.helloyoonsoo.com/",
  //   "http://www.jmine.net",
  //   "http://habi-unni.com",
  //   "http://www.sovomall.co.kr",
  //   "http://www.annadiva.com/",
  //   "http://www.styleonme.com/",
  //   "http://www.roniel.co.kr/",
  //   "http://aboutsome.co.kr/",
  //   "http://www.pinksisly.com/",
  //   "http://www.sunny11.com/",
  //   "http://www.nanasalon.com/",
  //   "http://luxwiz.com/",
  //   "http://www.deepny.com/",
  //   "http://www.build.co.kr/",
  //   "http://www.hypnotic.co.kr",
  //   "http://vi-shop.kr/",
  //   "http://magjay.com/",
  //   "http://nibbuns.co.kr/",
  //   "http://www.dorosiwa.co.kr/",
  //   "http://k-club.co.kr",
  //   "http://www.under-vi.com/",
  //   "https://www.skullpig.com/",
  //   "http://soim.co.kr",
  //   "http://www.veryyou.co.kr/",
  //   "http://www.chicfox.co.kr",
  //   "http://www.dodry.net/",
  //   "http://cocojane.net",
  //   "http://www.realcoco.com/",
  //   "http://mjcong.co.kr",
  //   "http://www.uptownholic.com/",
  //   "http://www.la-duna.co.kr/",
  //   "http://www.midasb.co.kr",
  //   "http://anais.co.kr",
  //   "http://reine.co.kr",
  //   "http://www.45th.co.kr/",
  //   "http://www.nak21.com/",
  //   "http://www.discosalon.co.kr",
  //   "http://www.alittle-b.com/",
  //   "http://www.ojluxury.com/",
  //   "http://thezam.co.kr",
  //   "http://www.pippin.co.kr",
  //   "http://loloten.com/",
  //   "http://www.twang.co.kr/",
  //   "http://www.trendy-apparel.co.kr/",
  //   "http://www.recipeofgirl.com/",
  //   "http://www.pureda.co.kr",
  //   "http://gumzzi.co.kr",
  //   "http://www.pinkage.co.kr/",
  //   "http://www.ellpe.co.kr/",
  //   "http://haselmode.co.kr",
  //   "http://www.maybeach.co.kr/",
  //   "http://www.runo.co.kr/",
  //   "http://www.ba-on.com",
  //   "http://www.withyoon.com",
  //   "http://www.nicehong.com/",
  //   "http://badblood.co.kr/",
  //   "http://kwonjo.co.kr",
  //   "http://www.citynwoman.com/",
  //   "http://www.itshu.co.kr/",
  //   "http://gogirl.co.kr",
  //   "http://www.feminique.kr/",
  //   "http://bikibiki.co.kr",
  //   "http://www.digue.com",
  //   "http://www.mina-gram.com/",
  //   "http://www.orange-flower.co.kr/",
  //   "http://www.na-mu.co.kr/",
  //   "http://www.pur-ple.co.kr/",
  //   "http://bylogin.co.kr/",
  //   "http://www.boen.co.kr/",
  //   "http://goldpang.com/",
  //   "http://www.fashion-full.com",
  //   "http://www.vikinivender.com/",
  //   "http://richmood.co.kr/",
  //   "http://www.gonyshop.com/",
  //   "http://www.sibuya.co.kr/",
  //   "http://www.theozzang.com",
  //   "http://www.another-j.com/",
  //   "http://www.henique.co.kr/",
  //   "http://www.smokyalice.com/",
  //   "http://www.hi-diva.com/",
  //   "http://monicaroom.com/",
  //   "http://www.shoemaru.com",
  //   "http://www.goldbutton.co.kr/",
  //   "http://marant.kr",
  //   "http://www.monobabie.com/",
  //   "http://www.iniesta.co.kr/",
  //   "http://perbit.co.kr/",
  //   "http://pighip.co.kr/",
  //   "http://sroom.co.kr",
  //   "http://www.sonyunara.com/",
  //   "http://www.sweetglam.co.kr/",
  //   "http://www.wingsmall.co.kr/",
  //   "https://linennatural.com/",
  //   "http://www.havanasunday.com",
  //   "http://www.bluepops.co.kr/",
  //   "http://kjoli.com/",
  //   "http://www.roxygirl.tv/",
  //   "http://www.ely-sia.net",
  //   "http://www.rilly.co.kr",
  //   "http://www.annarich.co.kr/",
  //   "http://www.ippngirl.co.kr/",
  //   "http://chocomom.com",
  //   "http://www.dailyjou.com/",
  //   "http://www.limishop.co.kr/",
  //   "http://www.iammari.com/",
  //   "http://www.happy10.co.kr/",
  //   "http://www.olssen.co.kr/",
  //   "http://www.fine-thankyou.com/",
  //   "https://www.creamcheese.co.kr/",
  //   "http://www.9grab.com/",
  //   "http://fromheadtotoe.kr/",
  //   "http://rekoi.kr/index.html",
  //   "http://www.salonl.co.kr/",
  //   "http://www.comesta.co/",
  //   "http://www.chic-de.com/",
  //   "http://darkvictory.co.kr/",
  //   "http://twee.co.kr/",
  //   "http://www.happymini.shop/",
  //   "http://www.misharp.co.kr",
  //   "http://www.labambaroom.com/",
  //   "http://shopperland.co.kr",
  //   "http://waniwani.co.kr/",
  //   "http://www.melrosemood.com/",
  //   "http://www.wearehere.co.kr/",
  //   "http://www.by-sun.com/",
  //   "http://www.lalame.net/",
  //   "http://www.moondal.com/",
  //   "http://www.indibrand.co.kr",
  //   "https://the-way.co.kr/",
  //   "http://www.momnuri.com",
  //   "http://shes-story.co.kr",
  //   "http://soo-soo.co.kr",
  //   "http://misscandy.co.kr",
  //   "http://vinvle.com/",
  //   "http://www.danilove.co.kr",
  //   "http://www.shehj.com",
  //   "http://hrb.kr",
  //   "http://www.kikiko.co.kr/",
  //   "http://www.iampretty.tv/",
  //   "http://hn-hn.co.kr/",
  //   "http://7v.co.kr",
  //   "http://www.mayddle.com",
  //   "http://www.choper.kr/",
  //   "http://www.manymore.co.kr/",
  //   "http://www.awab.co.kr/",
  //   "http://www.fromdayone.co.kr/",
  //   "http://www.ultrafashion.net",
  //   "http://www.tiramisustyle.com/",
  //   "http://www.wingbling.co.kr/",
  //   "http://www.realyellow.co.kr/",
  //   "http://www.suhelen.com/",
  //   "http://www.qng.co.kr",
  //   "http://www.timelady.co.kr/",
  //   "http://www.freckle.kr/",
  //   "http://www.walkingcoco.co.kr/",
  //   "http://www.ifgirl.co.kr",
  //   "http://utg.kr/",
  //   "http://www.in-themode.com",
  //   "http://aftermonday.com",
  //   "http://loveme.kr",
  //   "http://feelings.co.kr/",
  //   "http://matesales.com",
  //   "http://www.everymorning.co.kr/",
  //   "http://thejsoo.com",
  //   "http://secondesecon.com/",
  //   "http://www.ready-2-wear.co.kr",
  //   "http://www.noncode.co.kr/",
  //   "http://www.hollyshop.co.kr/",
  //   "http://www.vanillashu.co.kr/",
  //   "http://www.manymanymode.com",
  //   "http://www.looknone.co.kr",
  //   "http://candyglow.co.kr/",
  //   "http://kangsister.com/",
  //   "http://thewoman.kr",
  //   "http://www.high-eny.co.kr/",
  //   "http://www.dorocy.co.kr/",
  //   "http://www.merryat.com/",
  //   "http://www.g-r-a-b.com",
  //   "http://joyu.co.kr/",
  //   "http://devi-wear.com",
  //   "http://www.daltt.co.kr/",
  //   "http://www.annpiona.co.kr/",
  //   "http://www.coco-m.co.kr/",
  //   "http://www.byjungsoo.com",
  //   "http://lovelyshoes.co.kr/",
  //   "http://www.reticella.co.kr/",
  //   "http://9rumi.co.kr",
  //   "http://www.minibbong.co.kr/",
  //   "http://madejay.com",
  //   "http://www.addmore.co.kr",
  //   "http://www.lountess.com",
  //   "http://www.vivishoeshoe.com",
  //   "http://2lve12.com",
  //   "http://www.up-closet.com/",
  //   "http://www.realmommy.co.kr/",
  //   "http://www.queenspider.com/",
  //   "http://bbibbongunni.com",
  //   "http://www.junjewelry.com/",
  //   "http://www.rozley.co.kr",
  //   "http://www.likeher.kr/",
  //   "http://www.arima.co.kr/",
  //   "http://www.mimididi.co.kr/",
  //   "http://www.vanillasecond.com",
  //   "http://www.i-arden.com/",
  //   "http://www.myfiona.co.kr",
  //   "http://www.luvmiu.com",
  //   "http://www.thecocomj.co.kr/",
  //   "http://www.pink-rocket.com",
  //   "http://www.springcomma.com/",
  //   "http://www.sagestore.co.kr/product/list.html?cate_no=24",
  //   "http://www.bluecoco.co.kr/",
  //   "http://www.femmemuse.co.kr",
  //   "http://www.apuesto.co.kr",
  //   "http://threecut.kr/",
  //   "http://cocond.com",
  //   "http://www.lusida.co.kr/",
  //   "http://www.goroke.co.kr",
  //   "http://dparks.co.kr/",
  //   "http://www.byyoom.co.kr/",
  //   "http://sundayup.co.kr",
  //   "http://www.gabalnara.com/",
  //   "http://www.goldria.net",
  //   "http://www.shebeach.co.kr/",
  //   "http://yonifit.co.kr",
  //   "http://www.noran-otjang.co.kr/",
  //   "http://www.5zzil.com",
  //   "http://www.everafter.kr",
  //   "http://www.sistershu.com",
  //   "http://heigl.kr/",
  //   "http://www.a-miu.com/",
  //   "http://www.9-room.com/",
  //   "http://jtamtam.co.kr/",
  //   "http://www.gogobeach.co.kr/",
  //   "http://www.whosgirl.co.kr",
  //   "http://www.m-jade.co.kr",
  //   "http://www.dalkijam.net/",
  //   "http://binary01.co.kr",
  //   "http://www.nanajean.co.kr/",
  //   "http://toring.co.kr/",
  //   "http://www.graymadonna.com/",
  //   "http://www.camelbrown.com/",
  //   "http://www.creccendo.com/",
  //   "http://02sister.com",
  //   "http://archei.co.kr/",
  //   "http://envylook.com",
  //   "http://www.zuwa.co.kr",
  //   "http://www.madol.kr/",
  //   "http://www.liveary.com",
  //   "http://www.tograndmother.co.kr/",
  //   "http://www.bullang.com/",
  //   "http://www.voga.co.kr",
  //   "http://www.loveandpop.kr/",
  //   "http://www.dona-d.com/",
  //   "http://www.myclassy.co.kr/",
  //   "http://www.thedaze.kr",
  //   "http://www.174.co.kr/",
  //   "http://onepound.kr/",
  //   "http://augustplan.com/",
  //   "http://disbunnystar.co.kr",
  //   "http://simkung.co.kr",
  //   "http://www.aesoo.co.kr/",
  //   "http://www.afairyfit.com",
  //   "http://www.jooen.com/",
  //   "http://www.finchvill.com/",
  //   "https://gifteabox.com",
  //   "http://blessshop.co.kr/",
  //   "http://www.jblanc.kr/",
  //   "http://conella.co.kr/",
  //   "http://www.byroh.com",
  //   "http://darllyshop.co.kr/",
  //   "http://www.mizmin.co.kr/",
  //   "http://www.show-me.kr/",
  //   "http://theresheis.kr/index.html",
  //   "http://www.browncode.co.kr/",
  //   "http://www.againby.com",
  //   "http://nabiang.com",
  //   "http://m-style.co.kr/",
  //   "http://www.osimoto.co.kr/",
  //   "http://www.viewlap.com",
  //   "http://www.uuzone.co.kr",
  //   "http://wittyb.com/",
  //   "http://www.robinu.co.kr/",
  //   "http://www.balibiki.net/",
  //   "http://www.a-monotone.com",
  //   "http://www.youbyeolna.com",
  //   "http://www.cosmicray.co.kr/",
  //   "http://www.localmansion.com/",
  //   "http://blank9.com/",
  //   "http://www.merongshop.com/",
  //   "http://lalaroom.co.kr",
  //   "http://www.openithere.com/",
  //   "http://www.crazygirls.co.kr/",
  //   "http://www.gosister.co.kr",
  //   "http://another-language.com/",
  //   "http://www.mu-mu.co.kr/",
  //   "http://thexxxy.com/",
  //   "http://www.amai.co.kr/",
  //   "http://www.nadri4u.com",
  //   "http://www.sezwick.com",
  //   "http://www.styletiba.com/",
  //   "http://dancegirl.co.kr/",
  //   "http://ssomedays.com",
  //   "http://www.906studio.co.kr/",
  //   "http://www.whosbag.com/",
  //   "http://www.barbiecoco.co.kr/",
  //   "http://bonjourproject.kr/",
  //   "http://www.arnewstyle.com/",
  //   "http://www.gabangpop.co.kr",
  //   "http://www.marhenbreeze.com",
  //   "http://www.wansmall.com",
  //   "http://sn-sn.co.kr/",
  //   "http://www.mariang.co.kr/",
  //   "https://jennyberry.kr/",
  //   "http://urban-rosy.com/",
  //   "http://www.shesday.com/",
  //   "http://chaefit.com",
  //   "http://the-mono.com",
  //   "http://blackthefit.com/",
  //   "http://www.themode.co.kr",
  //   "http://www.ilt-shop.co.kr/",
  //   "http://vastcharm.kr/",
  //   "http://www.derang.me/",
  //   "http://www.the-wish.co.kr/",
  //   "http://www.maxnchic.com/",
  //   "http://www.mixxmix.com/",
  //   "http://www.planj.co.kr",
  //   "http://www.feelsogirl.com/",
  //   "http://www.lookatmin.com",
  //   "http://locobonita.com",
  //   "http://www.dailymarket.kr/",
  //   "http://www.moremoment.com/",
  //   "http://www.minzzang.co.kr",
  //   "http://www.lilyti.com/",
  //   "http://rowky.com/",
  //   "http://luv-in-up.com",
  //   "http://www.ssoaeng.co.kr",
  //   "http://simpleboutique.co.kr/",
  //   "http://www.daybin.co.kr/",
  //   "http://www.a-in.kr",
  //   "http://hotissue.or.kr",
  //   "http://www.more-cherry.com/",
  //   "http://www.pinksecret.co.kr/",
  //   "http://girlscase.co.kr/",
  //   "http://www.bonzishop.com",
  //   "http://itdancer.com/",
  //   "http://www.gildongsangsa.com/",
  //   "http://di-blanc.co.kr/",
  //   "http://www.monacogirls.co.kr",
  //   "http://www.globalyard.com",
  //   "http://www.wiarae.com/",
  //   "http://belin.co.kr",
  //   "http://www.ping-nugget.com/",
  //   "http://www.hwangbarbie.com/",
  //   "http://onesta.co.kr/",
  //   "http://inthecloset.kr",
  //   "http://21dressroom.com/",
  //   "http://ssomuch.com/",
  //   "http://www.cookiemaru.kr",
  //   "http://www.rurugold.com/",
  //   "http://mimibabi.com",
  //   "http://www.tongkeungirl.com",
  //   "http://www.c-chouette.co.kr/",
  //   "http://www.jjoodd.com/",
  //   "http://www.meltingblue.co.kr/",
  //   "http://www.windygirl.co.kr/",
  //   "http://j-blin.com",
  //   "http://www.pak-namae.com",
  //   "http://www.wannabej.com/",
  //   "http://dryrose.co.kr/",
  //   "http://vivashoo.co.kr",
  //   "http://www.exabra.com",
  //   "http://alldayu.com",
  //   "https://peachvin.com/",
  //   "http://lavu.co.kr/",
  //   "http://www.linea-storia.co.kr/",
  //   "http://www.stylebiggirl.co.kr/",
  //   "http://bloggerbok.co.kr/",
  //   "http://u-inme.com/",
  //   "http://dorosibeach.com",
  //   "http://mix-b.co.kr/",
  //   "http://flat-80.com/",
  //   "http://www.applecock.com",
  //   "http://www.leika.co.kr/",
  //   "http://p-sophia.com/",
  //   "http://luxyqueen.net/",
  //   "http://www.comeonvincent.com",
  //   "http://dressupp.net",
  //   "http://www.zanne.co.kr/",
  //   "http://www.babinpumkin.com",
  //   "http://www.cottoncandystore.co.kr/",
  //   "http://www.holia.co.kr/",
  //   "http://www.nabyup.com",
  //   "http://www.roseheel.com/",
  //   "http://ibelin.co.kr",
  //   "http://www.cho2shop.com",
  //   "http://argen.kr/",
  //   "http://www.themini.co.kr/",
  //   "http://blackpeach.co.kr",
  //   "http://missright.co.kr",
  //   "http://yansae.com/",
  //   "http://bodymore.co.kr",
  //   "http://cocogen.co.kr/",
  //   "http://www.lovingcoco.kr",
  //   "http://www.somemood.co.kr/",
  //   "http://www.beachpalm.co.kr/",
  //   "http://www.gyul-factory.com/",
  //   "http://www.momentdive.co.kr/",
  //   "http://flyings.co.kr/",
  //   "http://www.mybany.com/",
  //   "http://www.ponyzn.com/",
  //   "http://www.saintmary.co.kr",
  //   "http://www.chamar.co.kr/",
  //   "http://www.bonnieshop.co.kr/",
  //   "http://asmama.com/",
  //   "http://www.dodostyle.com/",
  //   "http://www.3threecrown.com",
  //   "http://www.bit-da.com",
  //   "http://www.thecocoshop.co.kr/",
  //   "http://www.kijakeunyeoja.com/",
  //   "http://www.luzzibag.com/",
  //   "http://www.ma-ren.com",
  //   "http://bebeche.com",
  //   "http://www.happymaman.co.kr/",
  //   "http://www.luvj.co.kr/",
  //   "http://drawingonyou.com",
  //   "http://www.somedayif.com",
  //   "http://www.280days.co.kr/",
  //   "http://www.womensskill.com/",
  //   "http://www.thedalkom.co.kr/",
  //   "http://moodinslow.com",
  //   "http://www.alicegohome.co.kr/",
  //   "http://newmonday.co.kr/",
  //   "http://www.byme.co.kr/",
  //   "http://www.cobaltvin.co.kr/",
  //   "http://www.roer.co.kr",
  //   "http://lovelingjewelry.com/",
  //   "http://andoo.co.kr",
  //   "http://www.thejane.co.kr/",
  //   "http://www.hodoostory.com/",
  //   "http://www.flybeach.co.kr",
  //   "http://www.yebbum.co.kr/",
  //   "http://www.withmoment.co.kr",
  //   "http://www.kuchimachi.com",
  //   "http://stdevos.com",
  //   "http://www.awsomej.co.kr/",
  //   "http://www.vividplan.co.kr/",
  //   "http://urbanroom.co.kr",
  //   "http://leedsbecoming.com",
  //   "http://www.close-clip.com",
  //   "http://hot-10.com",
  //   "http://www.ontheriver.co.kr/",
  //   "http://unipopcorn.com/",
  //   "http://www.lalabong.co.kr/",
  //   "http://www.gabalmania.com/",
  //   "http://melted.co.kr/",
  //   "http://abgle.co.kr",
  //   "http://bonnyandbunny.com",
  //   "http://www.withmari.co.kr/",
  //   "http://maysome.com",
  //   "http://www.stayon.co.kr/",
  //   "http://www.dangolunni.com",
  //   "http://endorsi.kr/",
  //   "http://shoes-opening.com",
  //   "http://haepp.co.kr",
  //   "http://cosmocrats.co.kr",
  //   "http://www.blackhole-j.com/",
  //   "http://theyoons.co.kr",
  //   "http://maylime.co.kr",
  //   "http://www.buttonoff.co.kr",
  //   "http://www.blann.co.kr/",
  //   "http://www.ernieandz.com/",
  //   "http://bolsurokmaeryeok.com",
  //   "http://www.myclosetme.com/",
  //   "http://www.peachpicnic.com/",
  //   "http://www.carriescloset.co.kr/",
  //   "http://www.depuang.co.kr/",
  //   "http://www.modinedeseine.com/",
  //   "http://cherryville.co.kr",
  //   "http://delightmoon.kr/",
  //   "http://www.hijjoo.com",
  //   "http://nyeong-closet.com/",
  //   "http://www.shoesone.co.kr/",
  //   "http://www.rooseoin.com",
  //   "http://www.itme.kr/",
  //   "http://wwwcong.com/",
  //   "http://www.xn--2n1ba37ju43bca.com/",
  //   "http://hana-beach.com",
  //   "http://www.white-fox.co.kr",
  //   "http://blingshop.co.kr",
  //   "http://www.yan-story.com/",
  //   "http://paranormal.co.kr",
  //   "http://thecollective.co.kr/",
  //   "http://bubbledoll.kr/",
  //   "http://benign.co.kr/",
  //   "http://www.taranco.co.kr/",
  //   "http://www.merrydate.co.kr/",
  //   "http://la-mant.co.kr",
  //   "http://bbaeddak-goodoo.com",
  //   "http://www.healing-day.co.kr/",
  //   "http://leming.co.kr",
  //   "http://www.byyenn.co.kr/",
  //   "http://www.levernis.co.kr",
  //   "http://yuridosi.co.kr",
  //   "http://www.dal-som.com/",
  //   "http://1015mk.com",
  //   "http://www.zizik9.co.kr/",
  //   "http://www.ddenne.com/",
  //   "http://www.inthe-moment.co.kr/",
  // ];
  const test = [];
  return (
    <>
      <button
        onClick={async () => {
          urlList.forEach(async (url) => {
            const localData = JSON.parse(window.localStorage.getItem("data"));
            const result = await fetch(`/api/get-email?url=${url}`);
            const result2json = await result.json();
            test.push({ url, res: result2json.res });
          });
        }}
      >
        get email
      </button>
      <button
        onClick={() => {
          console.log(test);
        }}
      >
        결과보기
      </button>
      <button
        onClick={() => {
          console.log(fail);
        }}
      >
        실패보기
      </button>
    </>
  );
}
